# 1. Import Basic Python Package

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.pylab import rcParams

# 2. 了解問題：
(1) 定義問題：??(2) 蒐集資料

In [2]:
from sklearn.datasets import load_iris
iris_data = load_iris()
print(iris_data.keys())

dict_keys(['DESCR', 'target_names', 'data', 'feature_names', 'target'])


In [3]:
print(iris_data.DESCR)

Iris Plants Database

Notes
-----
Data Set Characteristics:
    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20  0.76     0.9565  (high!)
    ============== ==== ==== ======= ===== ====================

    :Missing Attribute Values: None
  

In [4]:
# Features
print(iris_data.data)
print(iris_data.data.shape)

[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]
 [ 5.4  3.9  1.7  0.4]
 [ 4.6  3.4  1.4  0.3]
 [ 5.   3.4  1.5  0.2]
 [ 4.4  2.9  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.4  3.7  1.5  0.2]
 [ 4.8  3.4  1.6  0.2]
 [ 4.8  3.   1.4  0.1]
 [ 4.3  3.   1.1  0.1]
 [ 5.8  4.   1.2  0.2]
 [ 5.7  4.4  1.5  0.4]
 [ 5.4  3.9  1.3  0.4]
 [ 5.1  3.5  1.4  0.3]
 [ 5.7  3.8  1.7  0.3]
 [ 5.1  3.8  1.5  0.3]
 [ 5.4  3.4  1.7  0.2]
 [ 5.1  3.7  1.5  0.4]
 [ 4.6  3.6  1.   0.2]
 [ 5.1  3.3  1.7  0.5]
 [ 4.8  3.4  1.9  0.2]
 [ 5.   3.   1.6  0.2]
 [ 5.   3.4  1.6  0.4]
 [ 5.2  3.5  1.5  0.2]
 [ 5.2  3.4  1.4  0.2]
 [ 4.7  3.2  1.6  0.2]
 [ 4.8  3.1  1.6  0.2]
 [ 5.4  3.4  1.5  0.4]
 [ 5.2  4.1  1.5  0.1]
 [ 5.5  4.2  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.   3.2  1.2  0.2]
 [ 5.5  3.5  1.3  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 4.4  3.   1.3  0.2]
 [ 5.1  3.4  1.5  0.2]
 [ 5.   3.5  1.3  0.3]
 [ 4.5  2.3  1.3  0.3]
 [ 4.4  3.2  1.3  0.2]
 [ 5.   3.5

In [5]:
# Label
print(iris_data.target) 
print(iris_data.target.shape) 

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
(150,)


# 2. Training and Testing Split
為了統一大家預測的結果請大家設定random_state=40,shuffle=True

In [6]:
from sklearn.model_selection import train_test_split
# split the data into training and validation sets
X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target, test_size=0.33, random_state=40
                                                    , shuffle=True)

# 3. Classify Iris: Simple Logistic Regression

In [7]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train,y_train)
y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

# 4. Prediction Result Evaluation

In [8]:
from sklearn import metrics
print('train evaluation---------------------------------')
print('accuracy:%.2f'%metrics.accuracy_score(y_train, y_train_pred))
print('confusion matirx:\n', metrics.confusion_matrix(y_train, y_train_pred))
print('test evaluation---------------------------------')
print('accuracy:%.2f'%metrics.accuracy_score(y_test, y_test_pred))
print('confusion matirx:\n', metrics.confusion_matrix(y_test, y_test_pred))

train evaluation---------------------------------
accuracy:0.97
confusion matirx:
 [[32  0  0]
 [ 0 33  2]
 [ 0  1 32]]
test evaluation---------------------------------
accuracy:0.96
confusion matirx:
 [[18  0  0]
 [ 0 13  2]
 [ 0  0 17]]


# 5. Logistic Regression Probability Output

In [9]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train,y_train)
y_test_pred = model.predict(X_test)
y_test_pred_proba = model.predict_proba(X_test)
print('Classification Output:\n', y_test_pred)
print('Probability Output:\n', y_test_pred_proba)

Classification Output:
 [0 2 2 2 1 2 1 1 2 0 1 0 0 2 1 2 2 2 1 1 2 2 1 0 1 0 0 2 0 1 1 0 0 0 0 2 0
 0 2 0 0 1 2 2 2 0 2 2 1 0]
Probability Output:
 [[  8.20766401e-01   1.79040983e-01   1.92615841e-04]
 [  1.62860065e-02   4.44465841e-01   5.39248153e-01]
 [  1.81127337e-03   2.21966629e-01   7.76222098e-01]
 [  3.60117224e-04   2.88883445e-01   7.10756438e-01]
 [  2.76034855e-02   6.22240519e-01   3.50155996e-01]
 [  1.06599586e-03   1.78043745e-01   8.20890260e-01]
 [  4.95273912e-03   5.65147326e-01   4.29899935e-01]
 [  2.57204796e-02   6.09361146e-01   3.64918374e-01]
 [  1.40015753e-02   3.95384147e-01   5.90614277e-01]
 [  8.45597196e-01   1.54360782e-01   4.20223801e-05]
 [  1.26683625e-02   5.72730469e-01   4.14601169e-01]
 [  8.45521112e-01   1.54360242e-01   1.18645942e-04]
 [  8.81128447e-01   1.18821318e-01   5.02356010e-05]
 [  4.93411251e-03   4.03021760e-01   5.92044127e-01]
 [  1.49163422e-01   7.85383976e-01   6.54526015e-02]
 [  7.87157084e-04   2.01962027e-01   7.97

# 6. 調整C值

In [10]:
"""調整看看C看看預測結果"""
model = LogisticRegression(C=1)
model.fit(X_train,y_train)
y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)
print('train evaluation---------------------------------')
print('accuracy:%.2f'%metrics.accuracy_score(y_train, y_train_pred))
print('confusion matirx:\n', metrics.confusion_matrix(y_train, y_train_pred))
print('test evaluation---------------------------------')
print('accuracy:%.2f'%metrics.accuracy_score(y_test, y_test_pred))
print('confusion matirx:\n', metrics.confusion_matrix(y_test, y_test_pred))

train evaluation---------------------------------
accuracy:0.97
confusion matirx:
 [[32  0  0]
 [ 0 33  2]
 [ 0  1 32]]
test evaluation---------------------------------
accuracy:0.96
confusion matirx:
 [[18  0  0]
 [ 0 13  2]
 [ 0  0 17]]


# 7. 調整multi_class
multinomial或ovr哪個performance好呢？
提示： defaul的solver='liblinear'並不支援multi_class='multinomial'，直接寫會報錯，因此記得加上solver='sag'。

In [11]:
"""調整muti_class"""
model = LogisticRegression(solver='sag', multi_class='multinomial')
model.fit(X_train,y_train)
y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)
print('train evaluation---------------------------------')
print('accuracy:%.2f'%metrics.accuracy_score(y_train, y_train_pred))
print('confusion matirx:\n', metrics.confusion_matrix(y_train, y_train_pred))
print('test evaluation---------------------------------')
print('accuracy:%.2f'%metrics.accuracy_score(y_test, y_test_pred))
print('confusion matirx:\n', metrics.confusion_matrix(y_test, y_test_pred))

train evaluation---------------------------------
accuracy:0.98
confusion matirx:
 [[32  0  0]
 [ 0 33  2]
 [ 0  0 33]]
test evaluation---------------------------------
accuracy:1.00
confusion matirx:
 [[18  0  0]
 [ 0 15  0]
 [ 0  0 17]]


/Users/Jacklin/anaconda3/envs/tensor_flow_py3p5/lib/python3.5/site-packages/sklearn/linear_model/sag.py:326: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
